version: '3.8'

services:
    # tests-fonctionnels:
    #     build: .
    #     ports:
    #         - "5000:5000"
    db:
        image: postgres
        restart: always
        ports:
        - 5432:5432
        environment:
            POSTGRES_PASSWORD: password

